### ISSUE TITLE
Hide confusing warning message from setuptools

### ISSUE THREAD

**Issue by AAlon** [colcon/colcon-bundle#140] opened 2020-03-02 22:54 UTC
As a result of https://github.com/colcon/colcon-bundle/pull/127 an incompatible version of setuptools will not be installed. We need a way to hide the irrelevant warning:

```
You are running Setuptools on Python 2, which is no longer
supported and
>>> SETUPTOOLS WILL STOP WORKING <<<
in a subsequent release (no sooner than 2020-04-20).
```
Not sure the solution would be in colcon-bundle but perhaps it's possible for colcon-bundle to change the warning configuration when it prepares the bundle with setuptools.
Refer to internal issue B9SIM-1008.

**Comment by piraka9011** [comment] 2020-03-02 23:25
@AAlon this is related to setuptool and not to colcon-bundle.
Since the fix is in, I think what needs to happen instead is a version bump and customers should update their `colcon-bundle` install.

Looking into a bit tho, [I see that](https://github.com/pypa/setuptools/issues/1458#issuecomment-590461991) specifying `setuptools<45` instead of `setuptools==44` might work and/or adding:

```
import warnings
warnings.filterwarnings("ignore")
```

to `setup.py` is one way to suppress warnings.

**Comment by AAlon** [comment] 2020-03-02 23:47
re: not related to colcon-bundle - setuptools might not be a dependency of the customer's application. It's a dependency of pip, which is a dependency of colcon-bundle. So when customers bundle their ROS1 application, even if it has no use of setuptools - it will be bundled with Python2.x + setuptools (with the version that colcon-bundle decided). The customer has no control over that. Colcon-bundle could do something (rather ugly) like patch the warning message string of the setuptools installation in the bundle to be empty, or be less scary ;) Or patch the default warning config to filter out that particular one. Hopefully there are more elegant solutions out there.

**Comment by piraka9011** [comment] 2020-03-03 23:49
I wasn't able to reproduce locally and I don't think it's wise to suppress warnings.
I think the solution is to release colcon-bundle 0.0.19 with the latest changes which pin the setuptools version.

**Closed by piraka9011** 2020-03-03 23:49 UTC
Labels: question
